import { useNavigate } from "react-router-dom";
import { SUPPORT_EMAIL } from "../config.js";
import { DiscordLink } from "../components/ui.jsx";

const TIERS = [
  {
    name: "Branded Reports",
    price: "$99/mo",
    description: "Your logo and branding on every exported PDF report generated by MilCalc users.",
    bestFor: "VSOs, nonprofits, TAP programs",
    featured: false,
  },
  {
    name: "Embedded Calculator",
    price: "$299/mo",
    description: "Embed the full MilCalc experience directly on your website — no redirects, no co-branding.",
    bestFor: "Defense contractors, financial advisors",
    featured: true,
  },
  {
    name: "Full White Label",
    price: "$499/mo",
    description: "Your brand, your domain, your colors — powered by MilCalc's calculation engine under the hood.",
    bestFor: "Large VSOs, DoD transition programs",
    featured: false,
  },
];

export default function PartnersPage() {
  const navigate = useNavigate();

  return (
    <div style={{
      minHeight: "100vh",
      background: "#0f0f14",
      color: "#f9fafb",
      fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    }}>
      {/* Header */}
      <div style={{
        position: "sticky", top: 0, zIndex: 10,
        background: "rgba(15,15,20,0.95)", backdropFilter: "blur(8px)",
        borderBottom: "0.5px solid rgba(255,255,255,0.06)",
        padding: "12px 16px", display: "flex", alignItems: "center", gap: 12,
      }}>
        <button
          onClick={() => navigate(-1)}
          style={{
            background: "none", border: "none", color: "#9ca3af", fontSize: 14,
            cursor: "pointer", padding: "6px 0", fontFamily: "inherit",
            display: "flex", alignItems: "center", gap: 6,
          }}
        >
          ← Back
        </button>
      </div>

      {/* Hero */}
      <div style={{ maxWidth: 700, margin: "0 auto", padding: "40px 20px 16px", textAlign: "center" }}>
        <div style={{
          display: "inline-block", background: "rgba(212,160,23,0.1)",
          border: "0.5px solid rgba(212,160,23,0.3)", borderRadius: 20,
          padding: "4px 12px", fontSize: 11, fontWeight: 700,
          color: "#d4a017", letterSpacing: "0.08em", textTransform: "uppercase",
          marginBottom: 16,
        }}>
          For Organizations
        </div>
        <h1 style={{
          fontSize: 28, fontWeight: 700, color: "#d4a017",
          marginBottom: 12, lineHeight: 1.2,
        }}>MilCalc for Organizations</h1>
        <p style={{
          fontSize: 15, color: "#9ca3af", lineHeight: 1.6,
          maxWidth: 560, margin: "0 auto 40px",
        }}>
          Reach thousands of service members at the exact moment they are planning their transition.
          Choose the integration level that fits your program.
        </p>
      </div>

      {/* Tier cards */}
      <div style={{
        maxWidth: 700, margin: "0 auto", padding: "0 20px",
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
        gap: 16,
      }}>
        {TIERS.map(tier => (
          <div key={tier.name} style={{
            background: "#17171f",
            border: tier.featured
              ? "1.5px solid rgba(212,160,23,0.5)"
              : "0.5px solid rgba(255,255,255,0.06)",
            borderRadius: 14,
            padding: "22px 20px",
            display: "flex", flexDirection: "column",
            position: "relative",
          }}>
            {tier.featured && (
              <div style={{
                position: "absolute", top: -11, left: "50%", transform: "translateX(-50%)",
                background: "#d4a017", color: "#0f0f14",
                fontSize: 10, fontWeight: 700, letterSpacing: "0.08em",
                textTransform: "uppercase", borderRadius: 20, padding: "3px 10px",
                whiteSpace: "nowrap",
              }}>
                Most Popular
              </div>
            )}
            <div style={{ fontSize: 13, fontWeight: 700, color: "#f9fafb", marginBottom: 4 }}>
              {tier.name}
            </div>
            <div style={{
              fontSize: 22, fontWeight: 800,
              color: tier.featured ? "#d4a017" : "#f9fafb",
              marginBottom: 12,
            }}>
              {tier.price}
            </div>
            <p style={{ fontSize: 13, color: "#9ca3af", lineHeight: 1.6, flexGrow: 1, marginBottom: 12 }}>
              {tier.description}
            </p>
            <div style={{
              fontSize: 11, color: "#6b7280",
              borderTop: "0.5px solid rgba(255,255,255,0.06)",
              paddingTop: 10, marginBottom: 16,
            }}>
              <span style={{ color: "#4b5563", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.06em", fontSize: 10 }}>Best for</span>
              <br />
              {tier.bestFor}
            </div>
            <a
              href={`mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent(`MilCalc Partnership Inquiry — ${tier.name}`)}&body=${encodeURIComponent(`Hi,\n\nI'm interested in the ${tier.name} (${tier.price}) plan for MilCalc.\n\nOrganization name:\nUse case:\nEstimated users per month:\n\nPlease send details.\n`)}`}
              style={{
                display: "block", textAlign: "center",
                padding: "11px 16px",
                background: tier.featured ? "#d4a017" : "rgba(212,160,23,0.1)",
                color: tier.featured ? "#0f0f14" : "#d4a017",
                border: tier.featured ? "none" : "1px solid rgba(212,160,23,0.3)",
                borderRadius: 10, fontSize: 13, fontWeight: 700,
                textDecoration: "none", cursor: "pointer",
              }}
            >
              Get in touch →
            </a>
          </div>
        ))}
      </div>

      {/* Footer note */}
      <div style={{ maxWidth: 700, margin: "0 auto", padding: "40px 20px 64px", textAlign: "center" }}>
        <p style={{ fontSize: 13, color: "#4b5563", lineHeight: 1.6 }}>
          All plans include onboarding support and a dedicated contact for questions.
          Custom pricing available for enterprise programs serving 10,000+ users.
        </p>
        <p style={{ fontSize: 13, color: "#4b5563", marginTop: 8 }}>
          <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "#6b7280", textDecoration: "underline" }}>
            {SUPPORT_EMAIL}
          </a>
        </p>
        <DiscordLink />
      </div>
    </div>
  );
}
